# Generated by Django 2.1.7 on 2019-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=None)),
                ('fnlwgt', models.IntegerField(default=None)),
                ('education_num', models.IntegerField(default=None)),
                ('martial_status', models.CharField(default=None, max_length=200)),
                ('occupation', models.CharField(default=None, max_length=200)),
                ('relationship', models.CharField(default=None, max_length=200)),
                ('race', models.CharField(default=None, max_length=200)),
                ('sex', models.CharField(default=None, max_length=200)),
                ('capital_gain', models.IntegerField(default=None)),
                ('capital_loss', models.IntegerField(default=None)),
                ('hours_per_week', models.IntegerField(default=None)),
                ('native_country', models.CharField(default=None, max_length=200)),
                ('salary', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
