# Generated by Django 2.1.7 on 2019-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survaider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adults',
            name='work',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
