# Generated by Django 2.1.7 on 2019-02-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survaider', '0002_adults_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adults',
            name='age',
            field=models.IntegerField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='adults',
            name='capital_gain',
            field=models.IntegerField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='adults',
            name='capital_loss',
            field=models.IntegerField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='adults',
            name='education_num',
            field=models.IntegerField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='adults',
            name='fnlwgt',
            field=models.IntegerField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='adults',
            name='hours_per_week',
            field=models.IntegerField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='adults',
            name='martial_status',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='adults',
            name='native_country',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='adults',
            name='occupation',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='adults',
            name='race',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='adults',
            name='relationship',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='adults',
            name='salary',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='adults',
            name='sex',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='adults',
            name='work',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
    ]
