# Generated by Django 2.1.7 on 2019-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survaider', '0004_adults_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adultdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(db_index=True, default=None)),
                ('work', models.CharField(db_index=True, default=None, max_length=200)),
                ('fnlwgt', models.IntegerField(db_index=True, default=None)),
                ('education', models.CharField(db_index=True, default=None, max_length=200)),
                ('education_num', models.IntegerField(db_index=True, default=None)),
                ('martial_status', models.CharField(db_index=True, default=None, max_length=200)),
                ('occupation', models.CharField(db_index=True, default=None, max_length=200)),
                ('relationship', models.CharField(db_index=True, default=None, max_length=200)),
                ('race', models.CharField(db_index=True, default=None, max_length=200)),
                ('sex', models.CharField(db_index=True, default=None, max_length=200)),
                ('capital_gain', models.IntegerField(db_index=True, default=None)),
                ('capital_loss', models.IntegerField(db_index=True, default=None)),
                ('hours_per_week', models.IntegerField(db_index=True, default=None)),
                ('native_country', models.CharField(db_index=True, default=None, max_length=200)),
                ('salary', models.CharField(db_index=True, default=None, max_length=200)),
            ],
        ),
    ]
